version: "3"
services:
  conejito:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - 'rabbitmq_data:/data'
      # - ./rabbitmq.config:/etc/rabbitmq/rabbitmq.config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 20s
      retries: 50

  creator:
    build: ./creator/
    volumes:
      - ./creator:/data/creator
    ports:
      - 5000:5000
    links:
      - conejito
    restart: on-failure
    depends_on:
      - conejito

  notifications:
    build: ./notifications/
    volumes:
      - ./notifications:/data/notifications
    ports:
      - 8000:8000
    links:
      - conejito
    restart: on-failure
    depends_on:
      - conejito

  # worker-grouper:
  #   build: ./workers/
  #   volumes:
  #     - ./workers:/data/workers
  #   command: "python /data/workers/grouper.py"
  #   links:
  #     - conejito
  #   depends_on:
  #     - conejito

  # worker-single:
  #   build: ./workers/
  #   volumes:
  #     - ./workers:/data/workers
  #   command: "python /data/workers/single.py"
  #   links:
  #     - conejito
  #   depends_on:
  #     - conejito

  worker-event-dispatcher:
    build: ./workers/
    volumes:
      - ./workers:/data/workers
    command: "python /data/workers/event_dispatcher.py"
    links:
      - conejito
    restart: on-failure
    depends_on:
      - conejito

  worker-event-sender:
    build: ./workers/
    volumes:
      - ./workers:/data/workers
    command: "python /data/workers/event_sender.py"
    links:
      - conejito
      - notifications
    restart: on-failure
    depends_on:
      - conejito

volumes:
  rabbitmq_data:
